In [10]:
import pandas as pd
#loading the dataset
df = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\data-science-using-python\dirty_cafe_sales.csv") 
df1=df.copy()

In [11]:
# replace dirty values
df1.replace(["UNKNOWN","ERROR"], np.nan, inplace=True)


In [12]:
# convert numeric columns
df1["Quantity"] = pd.to_numeric(df1["Quantity"], errors='coerce')
df1["Price Per Unit"] = pd.to_numeric(df1["Price Per Unit"], errors='coerce')

In [13]:
# drop missing rows
df1 = df1.dropna()

In [14]:
# define X and y

X = df1[['Quantity','Price Per Unit']]
y = df1['Payment Method']

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [19]:
#croas validation-svc
cross_val_score(SVC(), X, y, cv=5)


array([0.32038835, 0.33333333, 0.32847896, 0.31877023, 0.33711507])

In [20]:
#cross validation- decision tree
cross_val_score(DecisionTreeClassifier(), X, y, cv=5)

array([0.35113269, 0.36245955, 0.32847896, 0.31877023, 0.3095624 ])

In [22]:
#logistic Regression
cross_val_score(LogisticRegression(), X, y, cv=5)

array([0.33171521, 0.33980583, 0.33333333, 0.31553398, 0.33873582])

In [23]:
#random Forest
cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=5)

array([0.35113269, 0.37378641, 0.33171521, 0.31877023, 0.30307942])

In [24]:
#cross validation -knn
cross_val_score(KNeighborsClassifier(), X, y, cv=5)

array([0.33009709, 0.35113269, 0.35113269, 0.34142395, 0.31280389])

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [26]:
model = RandomForestClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[69, 62, 70],
       [82, 48, 67],
       [80, 58, 82]])

In [28]:
print(accuracy_score(y_test, model.predict(X_test)))


0.3220064724919094
